-- AlterTable
ALTER TABLE `sell_items` ADD COLUMN `givenQuantity` INTEGER NULL DEFAULT 0,
    ADD COLUMN `remainingQuantity` INTEGER NULL DEFAULT 0,
    MODIFY `itemSaleStatus` ENUM('PENDING', 'DELIVERED', 'REJECTED', 'PARTIALLY_DELIVERED') NOT NULL DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE `sell_stock_correction_items` MODIFY `itemSaleStatus` ENUM('PENDING', 'DELIVERED', 'REJECTED', 'PARTIALLY_DELIVERED') NOT NULL DEFAULT 'PENDING';
